version: "3.8"
services:
  login:
    networks:
      - login-network
    build: .
    ports:
      - 8080:443
    depends_on:
      - kratos

  postgresd:
    networks:
      - kratos-network
    image: postgres
    environment:
      POSTGRES_USER: kratos
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: kratos
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

  kratos-migrate:
    networks:
      - kratos-network
    image: oryd/kratos:v0.4.6-alpha.1
    environment:
      - DSN=postgres://kratos:secret@postgresd:5432/kratos?sslmode=disable&max_conns=20&max_idle_conns=4
    command:
      migrate sql -e --yes
    depends_on:
      - postgresd

  kratos:
    networks:
      - login-network
      - kratos-network
    image: oryd/kratos:v0.4.6-alpha.1
    volumes:
      - ./kratos:/home/ory:ro
    environment:
      - DSN=postgres://kratos:secret@postgresd:5432/kratos?sslmode=disable&max_conns=20&max_idle_conns=4
    depends_on:
      - postgresd
      - mailslurper

  mailslurper:
    networks:
      - kratos-network
    image: oryd/mailslurper:smtps-latest
    ports:
      - 4436:4436
      - 4437:4437

networks:
  login-network:
    name: login-network
  kratos-network:
    name: kratos-network
